import localFont from "next/font/local";
import "./globals.css";
import NavbarCustom from "@/components/navbar";
import FooterCustom from "@/components/footer";
import TanstackProviders from "@/providers/tanstackProviders";
import ReduxProvider from "@/providers/reduxProviders";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ikea",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProviders>
          <ReduxProvider>
            <NavbarCustom />
            {children}
            <FooterCustom />
          </ReduxProvider>
        </TanstackProviders>
      </body>
    </html>
  );
}
